steps:

  - id: "Running docker-compose"
    name: 'docker/compose'
    args: ['-f', './docker-compose.cloudbuild.yml', 'up', '-d']

  - id: "Chown in /var/www"
    name: 'docker'
    args: ['exec','-u','root','-t','app','chown','-R','www-data:www-data','/var/www']

  - id: "Running docker ps"
    name: 'docker'
    args: ['ps']

  - id: "Running composer install"
    name: 'docker'
    args: ['exec', '-t', 'app', 'composer', 'install']

  - id: "Copying dotEnv"
    name: 'docker'
    args: ['exec', '-t', 'app', 'cp', './.env.example', '.env']

  - id: "Running key:generate"
    name: 'docker'
    args: ['exec', '-t', 'app', 'php', '/var/www/artisan', 'key:generate']

  - id: "Running migrations"
    name: 'docker'
    args: ['exec', '-t', 'app', 'php', '/var/www/artisan', 'migrate']

  - id: "Running PHPUnit"
    name: 'docker'
    args: ['exec', '-t', 'app', 'php', '/var/www/vendor/bin/phpunit', '-c', '/var/www/phpunit.xml']
